#ifndef INTERFACE_LOGO_H
#define INTERFACE_LOGO_H

#include "interface_logo.h"

const char* logo[] = {
/* columns rows colors chars-per-pixel */
"100 100 253 2 ",
"   c None",
".  c #000002",
"X  c #00030C",
"o  c #01090E",
"O  c #0A0B0C",
"+  c #000611",
"@  c #030C13",
"#  c #090E14",
"$  c #030D1A",
"%  c #051116",
"&  c #0A1116",
"*  c #02131B",
"=  c #0C141B",
"-  c #0E191E",
";  c #021A1E",
":  c #11161C",
">  c #121A1E",
",  c #151817",
"<  c #1A0E1E",
"1  c #28131B",
"2  c #011522",
"3  c #031C24",
"4  c #0C1D23",
"5  c #081727",
"6  c #141C22",
"7  c #191E24",
"8  c #161A27",
"9  c #00102D",
"0  c #291A25",
"q  c #381827",
"w  c #31132E",
"e  c #052024",
"r  c #0B2126",
"t  c #082229",
"y  c #152125",
"u  c #1A2125",
"i  c #15222A",
"p  c #1B242B",
"a  c #1E292F",
"s  c #1D2734",
"d  c #0D2735",
"f  c #22252B",
"g  c #242B2E",
"h  c #28272A",
"j  c #35232A",
"k  c #252C33",
"l  c #292D33",
"z  c #272938",
"x  c #342838",
"c  c #2C3335",
"v  c #2D343B",
"b  c #283538",
"n  c #333A3C",
"m  c #35373A",
"M  c #23302F",
"N  c #0B201F",
"B  c #49121E",
"V  c #54141E",
"C  c #471726",
"Z  c #581825",
"A  c #491D34",
"S  c #671928",
"D  c #75192A",
"F  c #6D1E32",
"G  c #48232B",
"H  c #492A36",
"J  c #552A35",
"K  c #562B34",
"L  c #67262C",
"P  c #662634",
"I  c #782A35",
"U  c #793339",
"Y  c #6D2C32",
"T  c #74141D",
"R  c #39423E",
"E  c #353C42",
"W  c #383D42",
"Q  c #262F43",
"!  c #513443",
"~  c #763745",
"^  c #6A394E",
"/  c #3B4343",
"(  c #3C4449",
")  c #384448",
"_  c #3D4C55",
"`  c #444849",
"'  c #4A524E",
"]  c #474D54",
"[  c #4C5353",
"{  c #4C5659",
"}  c #545A56",
"|  c #545B5B",
" . c #5A5D5B",
".. c #535756",
"X. c #5A5849",
"o. c #5D605D",
"O. c #595D62",
"+. c #444F62",
"@. c #5C6363",
"#. c #5C666A",
"$. c #5C6873",
"%. c #626564",
"&. c #646C6C",
"*. c #676A68",
"=. c #6B716E",
"-. c #656D72",
";. c #646B75",
":. c #6B7374",
">. c #6C7679",
",. c #6C7778",
"<. c #727573",
"1. c #747A75",
"2. c #737B7B",
"3. c #797C7A",
"4. c #726F6C",
"5. c #68545A",
"6. c #861828",
"7. c #981827",
"8. c #8D1B32",
"9. c #B91827",
"0. c #AB1829",
"q. c #87242D",
"w. c #832A36",
"e. c #852C3A",
"r. c #8A2B36",
"t. c #972A36",
"y. c #88323C",
"u. c #992E37",
"i. c #A9232D",
"p. c #B5232D",
"a. c #A72736",
"s. c #BB2734",
"d. c #AA343D",
"f. c #C71828",
"g. c #D71929",
"h. c #D30F2B",
"j. c #EC1A2C",
"k. c #D92634",
"l. c #C82530",
"z. c #E72638",
"x. c #FD2B3D",
"c. c #E42632",
"v. c #903346",
"b. c #A83746",
"n. c #B73446",
"m. c #D93649",
"M. c #D03143",
"N. c #E92E44",
"B. c #FF2D42",
"V. c #F42E44",
"C. c #E73445",
"Z. c #FF3345",
"A. c #FF354A",
"S. c #FF3B4C",
"D. c #F93946",
"F. c #FF3B54",
"G. c #E33C59",
"H. c #92474F",
"J. c #AE474F",
"K. c #9F6365",
"L. c #CF4451",
"P. c #FF434D",
"I. c #FB464D",
"U. c #FF4552",
"Y. c #FF4A55",
"T. c #FF435C",
"R. c #FF4D5B",
"E. c #F44956",
"W. c #FF535B",
"Q. c #E24853",
"!. c #FD5767",
"~. c #F84A67",
"^. c #FF6E73",
"/. c #DA686F",
"(. c #7D827C",
"). c #82847D",
"_. c #A58478",
"`. c #FF827B",
"'. c #767D82",
"]. c #6B7784",
"[. c #7B8487",
"{. c #7A8290",
"}. c #828582",
"|. c #858984",
" X c #848B8B",
".X c #898B88",
"XX c #8B928D",
"oX c #889086",
"OX c #94968D",
"+X c #848D94",
"@X c #8A9496",
"#X c #9A9C94",
"$X c #959A97",
"%X c #928F8A",
"&X c #9CA299",
"*X c #A3A49C",
"=X c #A5A89A",
"-X c #B1B19D",
";X c #979EA3",
":X c #8C9CA7",
">X c #9AA3A6",
",X c #9DABB2",
"<X c #AAACA4",
"1X c #A5A9A8",
"2X c #ACB2AA",
"3X c #B5B7AB",
"4X c #A8ADB3",
"5X c #ADB3B6",
"6X c #B2B4B3",
"7X c #BBBDB3",
"8X c #B6BBBB",
"9X c #B1AEA8",
"0X c #A09E95",
"qX c #FF908B",
"wX c #C0BEB9",
"eX c #D39D8C",
"rX c #BDC1B7",
"tX c #BCC1AE",
"yX c #C2C4B5",
"uX c #C3C4BC",
"iX c #C7CBBD",
"pX c #D3CFB9",
"aX c #BBC2C4",
"sX c #BACAD7",
"dX c #CBCCC3",
"fX c #C6CAC5",
"gX c #CDD1C8",
"hX c #D5D8C9",
"jX c #C8D2D4",
"kX c #D7D9D5",
"lX c #C8CFCD",
"zX c #E3DBCA",
"xX c #DCE2D7",
"cX c #E3E5DD",
"vX c #EBEBDB",
"bX c #E7E7D6",
"nX c #F4F3DC",
"mX c #EDE9D6",
"MX c #EDEDEC",
"NX c #E8EBE3",
"BX c #EDF1E4",
"VX c #F4F5E4",
"CX c #FCFCE5",
"ZX c #F3F4EB",
"AX c #FDFDED",
"SX c #F7F8E9",
"DX c #F3F4F3",
"FX c #FEFEF4",
"GX c #FFFFFE",
"HX c #F5F8F3",
"JX c #EFF0E8",
"KX c #D9E0E2",
"LX c #BCBCC6",
/* pixels */
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                    rXpXhXmXmXnXnXnXnXvXmXmXbXhXyX                                                                                      ",
"                                                                        nXCXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXGXFXAXmX                                                                        ",
"                                                                CXGXGXGXGXGXGXGXCXrX#X|.*.} ` m M u > u g / } *.).-XzXAXGXGXGXGXGXGXGXSX                                                                ",
"                                                          FXGXGXGXGXGXSX3X<.` = X O # % & = , = > - , > > = , = % # X . o M %.<XcXGXGXGXGXGXGX                                                          ",
"                                                    GXGXGXGXGXVX<X{ 8 @ O & , u > % X > 6 > - # X = > X o = 6 6 8 & X = 6 6 % @ o # W XXkXGXGXGXGXGX                                                    ",
"                                              GXGXGXGXGXSX$Xz + # > y u u u > o > =XiX. X . = ).CXhXxXnX#Xn . . . *.kXc . % u y u y & # o u 1.dXGXGXGXGXAX                                              ",
"                                          GXGXGXGXZX Xk + # 8 r r 0 y u > X u dXGXGXSXGXuXFXGXvX%.. NXFXFXGXGXgXGXGXbXGXvXo.. = 6 y Z p r y & O p [.SXGXGXGXGX                                          ",
"                                      GXGXGXGXlX( o = - 5 5 C 9.g.f.- o h hXGX=X> GX.  .yX|.& X 4 X vXFXAXCXCXFX=.. ;.GXAXGXAXn X 4 D h.t.G 4 * - % % ( fXGXGXGXGX                                      ",
"                                  GXGXGXGXdXn o > u u D 0.7.7.8.G 3 . %.GXyX& . GX<.# : O : 6 p p X VXFXAXAXAXFXZX. k gXAXCXAXGX&.. 3 6 q.q.7.f.6.i y 6 O k 5XGXGXGXGX                                  ",
"                                  GXFX9Xn # u r u e e w w C q C 7 O oXGXR . & %.AXo > 6 7 u u u p @ VXFXAXCXAXAXGXuX. ].GXCXCXFXGX*X% y x q q q C 8 5 6 r 6 # g <XGXGX                                  ",
"                                  GXGXo > r e Z h.h.9.9.f.f.0.s.2 7 GX. @ 8 o VX .o > 6 > 7 u u u + BXFXAXAXAXAXAXGXm k gXFXAXGXhXFX> e f.g.f.9.9.9.f.h.S t i 6 a GXFX                                  ",
"                                  GXGXu 4 D 6.D S D D D D F D 8.0 X gX .& > R NXo > 6 6 u 7 > u u + BXFXAXAXAXFXFXFXgX. +XGXGXGX1X4.# > I L P S F L S S D 8.D y m GXGX                                  ",
"                                  AXGXa > q q q q B q w w w w q 7 4 n kXX % 7X[ # > X @ , > > 7 u o cXFXAXFXAXFXFXGXGXX E lXGXGX&.R , - A x A C B B Z B q q j y v GXHX                                  ",
"                                  FXGXk N 9.g.f.9.9.9.9.9.9.f.h.0.3 . GXX = gX$ & c HX$X, . @ 6 > X cXGXAXFXGXGXZXNX[.'.. @XGXLXXXo ; 7.g.f.f.9.9.9.0.9.9.h.7.r v GXSX                                  ",
"                                  FXGXa r Z S Z S S D S D S F S 6.0 X ;XO.W ;.O , @ . [ KXGX'.. o X NXGXGXcXjXO.p . fXFX. W kX:X#.& f 6.D S S S S T S S Z P G r v GXDX                                  ",
"                                  HXGXa N G Z G C C C B B B V C Z 8 : u aX].> > k g & GX Xa :.GX6X. cXxX#X] . . . =.GXGX/ . @X].c ; > Z Z Z V V V B V V C Z C y m GXDX                                  ",
"                                  FXGXp ; l.c.g.g.g.g.f.f.g.j.j.j.j.5 . DX{.. OX@ . ZXk GXGX'.. > . CX. . . . . ` GXAXFXdX. [ sXX N g.c.j.l.s.l.f.l.k.k.l.h.6.r m GXDX                                  ",
"                                  HXGXi 6 0 q q C e ; $ * ; t 0 q q 0 % $Xk . NX. : @ GX| ;X6Xo > . SXGX8 NX X] GXAXFXFXGX+ + +X& 0 h 7 3 e e ; 9 3 h C C q q r v GXHX                                  ",
"                                  HXGXp - q.q.D 7.= ` `.qXK.= D 7.7.S 3 $ $ ' dX. > - . NXc . > 6 . VXGXGXxXGXGXAXAXGX#XGX1.o 6 r Z 0.t.3 8.j.Y.d.3 K 7.7.9.6.r M GXDX                                  ",
"                                  FXGXi 3 6.7.7.6.$ K.eXX , 5 S 8.D F 0 4 + iX<X$Xo > > X % 6 > & . ZXFXAXAXAXFXFXGX<XX.GXGX. 6 i D I F e i.j = Q.j C 6.F J j r l GXZX                                  ",
"                                  GXGX8 e 7.9.g.j.e o (.CX_.* D 9.9.f.j.3 . GXGX%Xo : > > > > . c [ BXGXAXAXAXFXGXMX+ wXjXGX..% 7.g.s.n.; a.G % a.G L g.l.g.q.r c GXNX                                  ",
"                                  GXGXi 5 F I J H * H.J.1 qX$ Z I I I 8 % 2.FX{ *X+ 6 > > > O 1XGXkX6XNXFXFXAXGXMX$.. hX[ ,XlXo * D L L ; H.J.H.P.e q S L Z G > c GXMX                                  ",
"                                  GXGXp 5 S Z Z C 3 2 K./.m 3 q V S T 0 % [.. @.}.# , 7 > > o aX. . . . u GXFXGX+X8 X SXO.. 2.= 3 S Z Z ; h ~ U ; e h S L T B r c GXMX                                  ",
"                                  FXGXs ; s.k.k.z.7.q : 4 q S z.c.c.c.u 3 % % :.4.# : ( & : , & GX .X . uXGXGXaX] . O.kX'.O # - % s.k.M.L u y 4 u L x.k.l.g.q.N l GXDX                                  ",
"                                  nXSXp 4 1 1 0 0 0 B B V C 1 0 1 1 , , G K % <.*.& > y O.% > & k $X/ GXGXGXGX'.$ X 4X8X+Xo 0 Z q 1 0 0 q q C B Z B 0 1 0 q j y g FXBX                                  ",
"                                  pXkXf ; t.t.t.t.t.t.a.u.u.t.t.r.t.a.u.q.j - ' } = 6 > ) 8 6 > = . NXGXGXDX;X( o c 5X4X>XX 7 t.w.w.w.r.r.t.r.u.r.r.r.r.r.q.Z 6 l mXkX                                  ",
"        GXGXGXGXGXGXGXGXGXHXGXHXDXzXNXp ; 7.p.a.a.i.0.i.0.i.i.i.i.i.i.i.s.r 7 > , 6 6 y y u > y > = v ,XKXsX>X. o 1X4X,X5XX N r.9.s.p.p.p.p.p.p.s.s.s.p.p.l.7.N M nXbXBXZXHXFXGXGXGXGXGXGXGXGXSX        ",
"        AX*X@XOXOXOXOX$X#X#X#XOX#X2.1.y r I L L L L K Y L L L P L L L Y I y u u u 6 y y y u y 6 > 6 , X y ` f 6 y y 8 u s 6 - P Y Y I Y Y Y I U Y Y Y Y Y I L N f -.3.|.|..X.X}.}.}.)..X|.).<XAX        ",
"        CXW + % $ % + @ # * $ @ @ * 6 u u y 6 4 y r 6 4 e 4 4 4 4 4 r 4 r y y u u u 6 6 y 6 u 6 u y 6 4 : - 6 y , 6 u u u y > r 4 5 r r > y y N r * N y y r y u : @ & % = = = = # # = * % # ` FX        ",
"        CX..6 p = + W m X $ v p $ k > 6 y n = 4 = # $ v a % = % # 8 Q > = = 5 o X 6 y $ y v > - - 6 k @ a g o # ` g . 6 6 > k y 8 - = X X > y % = [ n X & y 8 o > ` & @ 7 7 $ # W k . > 7 6 [ AX        ",
"        CXo.= & ..GXGXGXGXm = GXGXfX. & . jXGXGXGXGXGX@.ZXGXGXGXGXGXl GXGXGXGXGX2X. xXGXFXm GXGX7 X &XGXGX. [.GXGXGXAX@ - - - GXGXGXGXGX<X. o 1.GXGXGXGXn o . 2XGXGXGX).X o 3.GXGXGXCX> 6 - [ AX        ",
"        nX .& % GXGXGXGXFXGX. 7XGXc @ , % a GXFXGXGXGX#.[ GXGXGXGXGXa &XFXGXGXGXGX1.( GX2.. GXGX1.X k GX:.> GXGXGXGXGXbX. 6 o |.GXGXGXGXGX|.. GXGXAXGXGXGX. [.GXGXFXGXGXW l GXGXVXGXGXhXX 6  .AX        ",
"        CX .% v GXVX. . AXGX. rXGXn # - = k GX3X. . o ( &.GX2.. . + p <XGX/ . :.GX$X] GX[.. GXFXuX. ) GX&.} GX2X. . GXGX. 6 + OXGX) . c GXNX7 GX7X. . pXGX8 hXGXn . <.GX[.} GX*X. . GXFX. 6  .SX        ",
"        CX .& k GXkXX o AXGX. 3XGXW # > = c GXuXo 6 4 + 1.GX+X@ 6 = . 2XGX{ o @.GXXX[ GX|.. GXAXGX. ) GX:.} GX$Xo X GXGX. 4 @ &XGXo.& @ GXBX= GX<X+ @ 7XGXa gXGXg &  .GX2.| GXOX$ o GXGXX 4 } SX        ",
"        CX@.# c GXdXX # fXhX+ rXGX` & > & n GXyXX 6 : @ 2.GX X$ 4 - X 2XGX{ o @.GX X{ GX X. GXAXGXk / GX:...GX$XX X cXBX. 6 o #XGX| & & GXNX, GX<X+ + yXGXk yXGXu # %.VX@.*.GX(.# > gX2Xo > ' nX        ",
"        CX .# E GXSX. > X . X yXGXn & - * / GXrXo 6 + @ (.GX X@ 4 o o 3XGX[ o @.GXXX| GXXX. GXvXGX[.R GX1.} GX$XX , . . 6 - @ =XGXo.# & GXNX, GX1X+ # yXGXz rXGXf & O . . %XGX&X. > X o 8 = ` nX        ",
"        CXo.$ # GXGX3X. - 6 o yXGXm & , & c GX<X. & 9X. <.GX:.. % <X. 3XGX[ @ { GX@X| GXoX. GX<XGXjXc GX2.} GX&X. - - > - - + <XGX .# % GXxX, GX<Xo # 7XGXm tXGXh # : : $ / GXGX<.. > 6 > , [ nX        ",
"        VX .- : y GXGXvX. % + 7XGXc # & = hXFXFXGXGX|.o VXFXGXGXGX).. rXGXR . ) GX>X{ GX|.X GX3XrXGXM GX2.o.GX#XX . . . = b R pXGX' X % GXkX= GX6XX $ 3XGXE 3XGXf . . . X X [ GXGX#X. 6 7 : } nX        ",
"        SX%.& 6 # - GXGXFXo X 7XGXc # = X [.GXGXGXGX}.. 2XGXGXGXGX:.. 3XGX2X6XFXGX1X[ GX(.. GX2X<.GX=.GX3. .GX&X. GXGXGXGXk X nXGX[ o 6 GXxXo GXuXX @ 3XGXW 6XGXO @.dXuXMX6 X ` GXGX*X. u , } nX        ",
"        VX%.= 6 6 , . DXGXnX. 7XGXc & : & n GXOX. o &.X :.GX%.X p %.. 1XGXGXGXGXNXX @.GX}.. GXrX6 GX<XGX3.} GX&X. GXGXGX. % + #XGX@.@ 8 GXxXX GXdXo $ 3XGXn wXGX% :.GXGX@.O > # g GXGX*.% 6 } mX        ",
"        VX%.= > % % , X GXGX: 7XGXn = 6 % n GX<Xo > # @ 3.GX:.@ > % + <XGX| k # . @ %.GX}.X GXfX. GXAXFX3. .GX$X. = hXGX. 4 @ &XGX| % u GXkXX GX7XX # wXGXl yXGXk # 3.GX%.o # , , f GXGXX 6 ..mX        ",
"        nX%.% v | %.& X dXGX> rXGXn , 6 % n GX9XX 6 - @ 1.GX>.@ > - o <XGX/ # 4 - @ &.GX}.. GXdX. gXCXFX2. .GX#X+ . kXGX. 6 @ OXGX| # p GXgX@ GX6X+ # yXGX, yXGXg + %.GX%.m | ] > X VXGXX 6 ..bX        ",
"        SXo.+ ] GXvXo X gXGXo 7XGXc , > % m GX<Xo 6 6 @ 3.GX>.# > > X <XGX` = > - @ %.GXK.X GXpX. }.AXFX<. .GXOXo X bXGX. 6 @ OXGX} @ a GXdX$ GX<XO @ wXGX: 3XGXf & *.GX$.K.GX@X$ X AXFXo > o.vX        ",
"        SXo.# ( GXwXX X pXGXX wXGXl = 6 @ v GX9Xo 7 - X ).GX<.# > = . 1XGX` % = = % %.GX{.X GXiX. n GXAX2. .GX%X+ X bXGX. 6 @ OXGX..o 6 GXuX6 GX=XX + yXGX8 wXGX, O %.GX-.*.GX3.& . CXAXX - [ nX        ",
"        VXo.$ ` GXiX. . hXGX+ wXGX= . . iX8 GX*X. . f #X&.GX| . . u O.OXGX` # = = @ @.GX[.% GXiXX . GXAX1.%.FXuX. . AXGX. 6 @ OXGX... 1.GXfX8 FXhX. . bXGXp uXGX' . oXGX=.%.FX#X. . AXFX. 6 [ VX        ",
"        VX%.= $ GXSXFXFXVXGX. 3XFXGXGXGXFXX GXFXGXGXGX4.O.GXGXGXGXGXv XXGX/ # = ; @ | GX1.. GXuX. o 3XFX3.7 GXZXFXGXGXGX. 6 @ OXSXGXGXFXGXXX. FXJXFXFXSXGX. 4.GXGXAXGXFX=.N GXZXGXGXSXvXX 4 ' VX        ",
"        SX%.- 4 z SXFXGXGX..# GXFXFXGXGXHX;.GXSXFXFXGX<.jXBXZXHXAXGX_ ZXSXlX. - , X gXAXNXO.FXGXa @ <.FX=X. O.GXGXGX= GXm - = GXSXZXAXBX2.. $ 7 hXGXGXZXc o . $XGXGX X2.cX. ` AXGXGXZX> > 6 ` VX        ",
"        VX%.- a 6 X c c o = p o + @ o o # = o + o X o : # + @ + + o k + @ = i y y y # X $ 8 X o p 8 # o = u % $ E @ % X y 8 6 o o @ + + * 8 7 - X 7 g . - y 8 $ # % o O ) 7 , o g 6 X > y 8 [ SX        ",
"        VX .- 8 y u 6 6 p p 8 i t r t t r t r r 4 t t 3 3 5 e 4 r 3 3 r r r e 3 3 3 3 e 3 5 e r 3 3 3 ; 3 3 3 3 3 3 3 3 3 3 3 4 r 5 r t e 3 3 3 5 ; ; 3 ; 3 4 r 3 5 3 4 4 p 7 p > 6 u u 7 6 ' VX        ",
"        SXm + = % + X X X % r J t.y.e.e.e.y.e.v.y.r.e.y.r.y.y.y.y.y.y.e.w.w.w.w.e.e.e.w.w.U e.w.w.e.e.y.y.r.r.w.w.I e.w.w.w.e.w.I w.I e.e.e.w.w.w.w.w.e.y.w.w.w.w.r.y.u.j 8 = . . X X o # + k SX        ",
"        GXGXGXGXGXGXGXGXGX%X% u.P.Y.Y.Y.P.F.R.R.T.U.E.T.I.D.Y.E.Y.I.S.R.I.I.Y.Y.W.W.Y.S.I.I.Y.S.I.Y.Y.Y.Y.P.D.S.S.Y.T.Y.U.Y.U.S.P.I.I.Y.W.Y.Y.P.Y.P.S.U.Y.P.S.U.S.P.P.Z.r.* uXGXGXGXGXGXGXGXGXFX        ",
"          , & O , h c , vX|.* r.A.n.K J !.Y.J ! x T.U ! x Q.K E.b.b.E.H F.e.L.L H H e.Q.U I.G ~.b.H.L.K H b.S.S.M.G H ^ E.G j Q.Y.y.J.n.H K x !.G !.R.J H R.U.H T.b.u.S.t.* <X=X. f h , &               ",
"                        NX.X* t.A.~ s J i !.2 v.b.U.< ^ a.U.2 !.~ $ ^.+ F.w ~ b.w 8 M.b.z R.X !.- J.v.u v.m.U.U.H.9 b.n.C.2 ~ + !.H ~ m.H t b.W.@ ^.! x H z !.9 ^ v.J F.t.* =X9X                        ",
"                        cX X* u.Z.v.! W.$ T.2 H.L.F.8 K.L.R.2 E.I + 5.9 T.x J F.e.! T.t.c !.2 Q.@ !.r.H /.S.D.F.v.z L.F.C.5 qXX !.P ~ F.J.n Y.R.+ ^.x v.G.2 !.9 $ H.^ F.u.% =X3X                        ",
"                        cX}.* t.B.r.J Y.2 T.3 8 J A.0 d C Y.3 G.8.+.+ $ ~.Q J A.I ! F.t.m R.J ! d Y.t.; : U.Z.A.v.2 t N.C.3 `.X W.Y ~ A.b.x U.Y.+ !.x a.L.2 T.9 5.* ~ S.a.* &XyX                        ",
"                        vX}.$ t.B.6.~ ^.2 F.3 !.T.x.5 G.F.U.2 G.w.H.< 9 !.E A B.U J T.r.H W.v.* ~ F.I ~ ~.A.x.A.v.H !.F.M.5 qXX Y.H y.D.b.7 F.Y.@ T.j a.Q.* S.5 G.@ ~ S.a.3 &XfX                        ",
"                        MX}.* t.B.F $ + b.F.9 $ + A.9 L.A.U.2 m.I ^ A.+ ~.Q ! A.~ j T.I m U.W.$ L.S.U * % P B.Z.v.2 2 C m.@ X h T.l I S.b.3 S.T.+ Y.m.2 2 v.B.9 F.8 K S.a.3 #XgX                        ",
"                        MX|.$ t.x.z.N.F.B.V.M.V.N.B.m.Z.B.x.N.x.N.V.B.V.B.N.F.B.C.m.Z.C.C.Z.S.M.Z.B.C.N.C.C.B.B.N.N.N.V.N.N.C.S.B.Q.D.B.C.C.B.Z.N.B.B.V.z.Z.B.N.B.B.x.Z.a.; $XkX                        ",
"                        MX.X$ n.Z.Z.Z.Z.A.A.S.S.A.B.A.Z.Z.B.B.B.B.Z.A.A.A.F.D.A.B.Z.Z.A.B.Z.A.A.A.Z.S.S.A.S.A.A.S.F.S.A.Z.A.S.S.Z.A.S.Z.Z.A.A.Z.A.Z.S.B.A.B.Z.Z.Z.Z.Z.S.l.3 $XkX                        ",
"                        MX3.@ 5 3 2 3 2 3 3 3 3 5 4 8 4 4 6 y 5 4 r * 3 ; * 8 6 = 5 8 6 $ 6 6 : 6 = % ; 4 3 % % * @ 3 3 5 $ ; ; 4 * % 3 * * 5 e 3 5 3 3 3 3 3 3 2 * % % 5 $ ).xX                        ",
"                        MX4.k v E z s i a i i * * 4 i i % o % ].O.X  XW W XX* a | s k Q ,Xs ( _ = n $.$.% % ,.-.b ,X+ _ u >X&.` X #.&.$ ] ] * @ 4 i 4 4 5 s 5 a s s b b W v OXKX                        ",
"                        MXDXDXMXMXDXHXHXHX9X% kXxX;.* - >XcX. >XjX. MX# $XO.a O.sXGX&.. @X. 6X` 5X@ kXb & @ jXb -._ 1X@X. 4X. >X. 4XaX. GX6X. KX) = ( xXjX= *.MXDXHXHXDXDXDXDXkX                        ",
"                                        . . ].$.5X,X4 6 & o o 4X$X. jXE  X. s O.| [.{ X {.. XX. jX. LX:.* @ 8X#.( kXi '.. +Xo [.X @X>X+ :.>X@ $ u o <X8X| -., .                                         ",
"                                            ..#.zXFXBX# u u % . . % . o X 2 @ X . . . o . @ X 4 @ 4 o % 6 6 . + @ . o . o . % ; @ . X $ X . y u X iXCXwX( '.                                            ",
"                                            . [.%XFXGX7XX = XX1X@XXX$X$X@X@X$X>X>X>X>X>X7XyX).& $ @ @ # = / 2X6X&X$X@X[. X+X{.{.@X+X{.[. X1X- & 1.GXFX[.>.O                                             ",
"                                              , >.9XGXGX..% o @.{.[.[.[.{. X X|.XXXXXX&XX X . g }.&X$X[.m . . . [.XXXX X|.(.[.K.3.3.<.=.=.X 4 u GXGX8X&.{                                               ",
"                                                ..2.gXGXGX, = f b c m c M c c c c l c k . :.FXSXGX) cXGXNXkX#X# > c c c x c l l l k l n k 8 . AXGXjX>.>.                                                ",
"                                                  ;.[.cXGXAX. - [ rX>X*X*X1X*X*X=X=X-XX |.FXW { X . BXFXGXo jXNX.  X&X#XOXOXOXOX%X%X=Xo.6 . iXGXDX[.:.O                                                 ",
"                                                  X :.$XBXGXkX. - 8 1X0X=X*X*X*X0X=X<X. $X4.$ X * + ZXFXGXFX+ 2X. '.2X9X<X*X*X*X#X=Xc , X OXGXFX;X&.c                                                   ",
"                                                    > :.*XFXGX=X. 6 v Q s Q z Q v z v # 2.= =.GX[.. FXFX6XXXW _ $ f z 7 z c l x h f > @ =.GXFX4X#.|                                                     ",
"                                                      { :.7XGXGX.XX % @XuX<X*X*X<X<XwX: = k 7 kXkXy }.) kX} GX. X <X<X*X*X0X%X=X#X= # ' GXFXfX#.,.                                                      ",
"                                                        -.>.fXGXGX4.+ # p LX6X5X5X4XLX[ + mX. XX& X GX|.b GX,X+ W LX9X6X5X6XwX4 $ @ ' GXGXfX-.>..                                                       ",
"                                                        . 1.>.gXGXGX<.X 6 8 z v z z z f $  Xp + = oXNXGXGXgX+.+ l E E Q 8 8 : 8 X @.GXGXaX-.2.&                                                         ",
"                                                          . >.2.uXGXGXoXX = ] fX7X6X8XgX@ o 6X. |.4.. $XGX;.$ @ dX6X1X<XkX] 6 X ).GXGXuX-.1.f                                                           ",
"                                                            . 2.:.5XGXGX3X. = X ` &X$X>X7X5 ( -.. # >.GX1Xv o 6X*X$X*X| X 6 . <XGXGX7X>.>.g                                                             ",
"                                                              . 2.-.1XHXGXVX& $ = W / v c : X ] {.+ NX1XE . 8 W z c E = = o xXGXHX4X-.2.n                                                               ",
"                                                                . 1.*.>XNXGXGX... & g 3XkXkX.XX + E v + X '.cXkXgX] % + / GXGXcX;X@.2.l                                                                 ",
"                                                                  . >.&. XkXGXGXrX. % % X -.$X&X>X&.&.%X%X}.4.. $ $ X &XGXGXdX@XO.'.,                                                                   ",
"                                                                    . -.:.:.8XFXGXGX .. > % ( }  .[ ` [ | | 6 4 X } FXGXFX6X>.#.'..                                                                     ",
"                                                                        n '.@.@XkXGXGXvXc X % # -.lXrX/ % $ X W vXGXGXkX$X#.2.-..                                                                       ",
"                                                                          . ,.&.1.4XZXGXGXgXM . @ # $ $ . ..bXGXGXJX6X'.#.[.m                                                                           ",
"                                                                              { '.#.'.8XFXGXGXvX@.. + 2.SXGXGXAXLX X#.>.2..                                                                             ",
"                                                                                O 1.'.&.[.rXZXGXGXAXGXGXGXBX8X+X&.:.[.`                                                                                 ",
"                                                                                    c [.'.-.[.8XNXGXGXkX8X X-.:.[.| .                                                                                   ",
"                                                                                        W  X2.=.[.aX>X[.-.1. X@..                                                                                       ",
"                                                                                          . `  X[.>.,.[.+Xo..                                                                                           ",
"                                                                                                u <.,.c .                                                                                               ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        ",
"                                                                                                                                                                                                        "
};



#endif // INTERFACE_LOGO_H
